bitplace/bitplace/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    #url(r'^$', 'bitplace.views.home', name='home'),
    url(r'^$', include('home.urls')),
    url(r'^market/', include('market.urls', namespace='market') ),
    url(r'^admin/', include(admin.site.urls)),
)

bitplace/home/urls.py
from django.conf.urls import patterns, include, url


urlpatterns = patterns('',
    url(r'^$', 'home.views.index', name='home'),
)

bitplace/market/urls.py
from django.conf.urls import patterns, include, url


urlpatterns = patterns('',
    url(r'^product/(?P<id>\d)/$', 'market.views.product', name='product'),
    url(r'^callback', 'market.views.callback', name='callback'),
    url(r'^pay', 'market.views.pay', name='pay'),
)

bitplace/home/models.py
from django.db import models

# Create your models here.

bitplace/market/models.py
from django.db import models
from django.contrib.auth.models import User


class Account(User):
    address = models.CharField(max_length=34, blank=False, null=False)


class Product(models.Model):
    account = models.ForeignKey(Account, blank=False, null=False)
    price = models.DecimalField(max_digits=6, decimal_places=4, blank=False, null=False)
    description = models.CharField(max_length=250)
    name = models.CharField(max_length=40)
    image_1 = models.ImageField(upload_to="/media", blank=False, null=False)
    image_2 = models.ImageField(upload_to="/media")
    app = models.FileField(upload_to="/media", blank=False, null=False)
    
    def __unicode__(self):
        return "Product #" + str(self.id)

class Payment(models.Model):
    PAYMENT_CHOICES = (
        ('CR', 'Created'),
        ('CH', 'Checked')
    )
    
    
    state = models.CharField(max_length=2, choices=PAYMENT_CHOICES, default="CR")
    input_address = models.CharField(max_length=34)
    product = models.ForeignKey(Product, blank=False, null=False)
    email = models.EmailField(blank=False, null=False)

bitplace/market/forms.py
from django import forms


class BuyForm(forms.Form):
    email = forms.EmailField(required=True)

bitplace/home/views.py
from django.shortcuts import render, render_to_response
from django.template import RequestContext


# Create your views here.


def index(request):
    return render_to_response(
        'home/index.html',
        {},
        context_instance=RequestContext(request)
    )

bitplace/market/views.py
from django.shortcuts import render, render_to_response, RequestContext, get_object_or_404, redirect
from django.http import HttpResponse

from .models import Payment
from .models import Product
from paymentwrapper.payment_wrapper import PaymentWrapper

def index(request):
    pass

def product(request, id):
    product = get_object_or_404(Product, id=id)
    return render_to_response('market/product.html', {'product':id}, RequestContext(request))

def callback(request):
    input_address = request.GET.get("input_address")
    payment = Payment.objects.get(input_address=input_address)
    payment.state = "CH"
    payment.save()
    return HttpResponse("ok")

def pay(request):
    product_id = request.POST.get("product_id")
    product = Product.objects.get(id=product_id)
    p = PaymentWrapper(product.price, product.account.address)
    input_address = p.generate()
    payment = Payment.objects.create(product=product, input_address=input_address)
    payment.save()
    return HttpResponse("pay to: " + input_address)

def download(request, input_address):
    input_address = request.GET.get("input_address")
    payment = Payment.objects.get(input_address=input_address)
    if payment.state == "Checked":
        pass #Download
    else:
        return HttpResponse("todavia no")

bitplace/templates/bootstrap-theme.html
        <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css" rel="stylesheet">

        <!--[if lt IE 9]>
          <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
        <link rel="shortcut icon" href="/bootstrap/img/favicon.ico">
        <link rel="apple-touch-icon" href="/bootstrap/img/apple-touch-icon.png">
        <link rel="apple-touch-icon" sizes="72x72" href="/bootstrap/img/apple-touch-icon-72x72.png">
        <link rel="apple-touch-icon" sizes="114x114" href="/bootstrap/img/apple-touch-icon-114x114.png">










        <!-- CSS code from Bootply.com editor -->

        <style type="text/css">
            .navbar-static-top {
  margin-bottom:20px;
}

i {
  font-size:16px;
}

.nav > li > a {
  color:#787878;
}

footer {
  margin-top:20px;
  padding-top:20px;
  padding-bottom:20px;
  background-color:#efefef;
}

/* count indicator near icons */
.nav>li .count {
  position: absolute;
  bottom: 12px;
  right: 6px;
  font-size: 10px;
  font-weight: normal;
  background: rgba(51,200,51,0.55);
  color: rgba(255,255,255,0.9);
  line-height: 1em;
  padding: 2px 4px;
  -webkit-border-radius: 10px;
  -moz-border-radius: 10px;
  -ms-border-radius: 10px;
  -o-border-radius: 10px;
  border-radius: 10px;
}

/* indent 2nd level */
.list-unstyled li > ul > li {
   margin-left:10px;
   padding:8px;
}
        </style>

bitplace/templates/center-column.html
{% load staticfiles %}

<div id="wrapper">
    <ul id="flip" class="ui-jcoverflip">
      <li title="The first image" class="ui-jcoverflip--item" style="left: 15px; bottom: 20px;">
        <img src="http://localhost:8000/static/img/1.png" style="width: 80px;"></li>
      <li title="A second image" class="ui-jcoverflip--item" style="left: 105px; bottom: 20px;">
        <img src="http://localhost:8000/static/img/2.png" style="width: 100px;"></li>
      <li title="This is the description" class="ui-jcoverflip--item" style="left: 215px; bottom: 0px;">
        <img src="http://localhost:8000/static/img/3.png" style="width: 200px;"></li>
      <li title="Another description" class="ui-jcoverflip--item" style="left: 425px; bottom: 20px;">
        <img src="http://localhost:8000/static/img/4.png" style="width: 100px;"></li>
      <li title="A title for the image" class="ui-jcoverflip--item" style="left: 535px; bottom: 20px;">
        <img src="http://localhost:8000/static/img/5.png" style="width: 80px;"></li>

        <span class="title ui-jcoverflip--title" style="display: none;">A title for the image</span>
        <span class="title ui-jcoverflip--title" style="display: none;">Another description</span>
        <span class="title ui-jcoverflip--title" style="">This is the description</span>
        <span class="title ui-jcoverflip--title" style="display: none;">A second image</span>
        <span class="title ui-jcoverflip--title" style="display: none;">The first image</span>
    </ul>
    <div id="scrollbar" class="ui-slider ui-slider-horizontal ui-widget ui-widget-content ui-corner-all">
        <a href="#" class="ui-slider-handle ui-state-default ui-corner-all" style="left: 50%;"></a>
    </div>
</div>

bitplace/templates/header.html
<div id="top-nav" class="navbar navbar-inverse navbar-static-top" style="margin-bottom:0;">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="icon-toggle"></span>
      </button>
      <a class="navbar-brand" href="#">BitMyApp</a>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">

        <li class="dropdown">
          <a class="dropdown-toggle" role="button" data-toggle="dropdown" href="#"><i class="glyphicon glyphicon-user"></i> Admin <span class="caret"></span></a>
          <ul id="g-account-menu" class="dropdown-menu" role="menu">
            <li><a href="#">My Profile</a></li>
          </ul>
        </li>
        <li><a href="#"><i class="glyphicon glyphicon-lock"></i> Logout</a></li>
      </ul>
    </div>
  </div>
</div>

bitplace/templates/home/index.html
{% extends "layout.html" %}

bitplace/templates/layout.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>BitPlace!</title>

    <!-- Bootstrap -->
    <link href="{% static "bootstrap/css/bootstrap.min.css" %}" rel="stylesheet">


    {% include "bootstrap-theme.html" %}
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    {% include "header.html" %}

    {% block main %}
    <div class="container">
      <div class="row">
        {% block sub_main %}{% endblock %}
      </div>
    </div>
    {% endblock %}
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="{% static "js/jquery.min.js" %}"></script>
    <script src="{% static "js/jquery-ui.min.js" %}"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{% static "bootstrap/js/bootstrap.min.js" %}"></script>

    <script src="{% static "jcoverflip/jquery.jcoverflip.js" %}" type="text/javascript"></script>
    <script type="text/javscript">
    $( document ).ready( function(){
        jQuery( '#flip' ).jcoverflip({
          current: 2,
          beforeCss: function( el, container, offset ){
            return [
              $.jcoverflip.animationElement( el, { left: ( container.width( )/2 - 210 - 110*offset + 20*offset )+'px', bottom: '20px' }, { } ),
              $.jcoverflip.animationElement( el.find( 'img' ), { width: Math.max(10,100-20*offset*offset) + 'px' }, {} )
            ];
          },
          afterCss: function( el, container, offset ){
            return [
              $.jcoverflip.animationElement( el, { left: ( container.width( )/2 + 110 + 110*offset )+'px', bottom: '20px' }, { } ),
              $.jcoverflip.animationElement( el.find( 'img' ), { width: Math.max(10,100-20*offset*offset) + 'px' }, {} )
            ];
          },
          currentCss: function( el, container ){
            return [
              $.jcoverflip.animationElement( el, { left: ( container.width( )/2 - 100 )+'px', bottom: 0 }, { } ),
              $.jcoverflip.animationElement( el.find( 'img' ), { width: '200px' }, { } )
            ];
          },
          change: function(event, ui){
            jQuery('#scrollbar').slider('value', ui.to*25);
          }
        });


        jQuery('#scrollbar').slider({
          value: 50,
          stop: function(event, ui) {
            if(event.originalEvent) {
              var newVal = Math.round(ui.value/25);
              jQuery( '#flip' ).jcoverflip( 'current', newVal );
              jQuery('#scrollbar').slider('value', newVal*25);
            }
          }
        });
      });


    </script>
  </body>
</html>

bitplace/templates/left-column.html
<div class="col-md-3">
  <!-- Left column -->
  <a href="#"><strong><i class="glyphicon glyphicon-wrench"></i> Tools</strong></a>

  <hr>

  <ul class="list-unstyled">
    <li class="nav-header"> <a href="#" data-toggle="collapse" data-target="#userMenu">
      <h5>Settings <i class="glyphicon glyphicon-chevron-down"></i></h5>
      </a>
        <ul class="list-unstyled collapse in" id="userMenu">
            <li class="active"> <a href="#"><i class="glyphicon glyphicon-home"></i> Home</a></li>
            <li><a href="#"><i class="glyphicon glyphicon-envelope"></i> Messages <span class="badge badge-info">4</span></a></li>
            <li><a href="#"><i class="glyphicon glyphicon-cog"></i> Options</a></li>
            <li><a href="#"><i class="glyphicon glyphicon-comment"></i> Shoutbox</a></li>
            <li><a href="#"><i class="glyphicon glyphicon-user"></i> Staff List</a></li>
            <li><a href="#"><i class="glyphicon glyphicon-flag"></i> Transactions</a></li>
            <li><a href="#"><i class="glyphicon glyphicon-exclamation-sign"></i> Rules</a></li>
            <li><a href="#"><i class="glyphicon glyphicon-off"></i> Logout</a></li>
        </ul>
    </li>
    <li class="nav-header"> <a href="#" data-toggle="collapse" data-target="#menu2">
      <h5>Reports <i class="glyphicon glyphicon-chevron-right"></i></h5>
      </a>

        <ul class="list-unstyled collapse" id="menu2">
            <li><a href="#">Information &amp; Stats</a>
            </li>
            <li><a href="#">Views</a>
            </li>
            <li><a href="#">Requests</a>
            </li>
            <li><a href="#">Timetable</a>
            </li>
            <li><a href="#">Alerts</a>
            </li>
        </ul>
    </li>
    <li class="nav-header">
    <a href="#" data-toggle="collapse" data-target="#menu3">
      <h5>Social Media <i class="glyphicon glyphicon-chevron-right"></i></h5>
      </a>

        <ul class="list-unstyled collapse" id="menu3">
            <li><a href="#"><i class="glyphicon glyphicon-circle"></i> Facebook</a></li>
            <li><a href="#"><i class="glyphicon glyphicon-circle"></i> Twitter</a></li>
        </ul>
    </li>
  </ul>

  <hr>

  <a href="#"><strong><i class="glyphicon glyphicon-link"></i> Resources</strong></a>

  <hr>

  <ul class="nav nav-pills nav-stacked">
    <li class="nav-header"></li>
    <li><a href="#"><i class="glyphicon glyphicon-list"></i> Layouts &amp; Templates</a></li>
    <li><a href="#"><i class="glyphicon glyphicon-briefcase"></i> Toolbox</a></li>
    <li><a href="#"><i class="glyphicon glyphicon-link"></i> Widgets</a></li>
    <li><a href="#"><i class="glyphicon glyphicon-list-alt"></i> Reports</a></li>
    <li><a href="#"><i class="glyphicon glyphicon-book"></i> Pages</a></li>
    <li><a href="#"><i class="glyphicon glyphicon-star"></i> Social Media</a></li>
  </ul>

  <hr>
  <ul class="nav nav-stacked">
    <li class="active"><a href="http://bootply.com" title="The Bootstrap Playground" target="ext">Playground</a></li>
    <li><a href="/tagged/bootstrap-3">Bootstrap 3</a></li>
    <li><a href="/61518" title="Bootstrap 3 Panel">Panels</a></li>
    <li><a href="/61521" title="Bootstrap 3 Icons">Glyphicons</a></li>
    <li><a href="/61523" title="Bootstrap 3 ListGroup">List Groups</a></li>
    <li><a href="#">GitHub</a></li>
    <li><a href="/61518" title="Bootstrap 3 Slider">Carousel</a></li>
    <li><a href="/62603">Layout</a></li>
  </ul>

  <hr>
</div>

bitplace/templates/market/product.html
{% extends "layout.html" %}

{% block main %}

<style type="text/css">
    .bs-docs-header {
        padding-top: 60px;
        padding-bottom: 60px;
        font-size: 24px;
        text-align: left;
    }
    .bs-docs-header {
        margin-bottom: 10px;
        font-size: 20px;
    }
    .bs-docs-masthead, .bs-docs-header {
        position: relative;
        padding: 30px 15px;
        color: #cdbfe3;
        text-align: center;
        text-shadow: 0 1px 0 rgba(0,0,0,.1);
        background-color: #6f5499;
        background-image: -webkit-linear-gradient(top,#563d7c 0,#6f5499 100%);
        background-image: linear-gradient(to bottom,#563d7c 0,#6f5499 100%);
        background-repeat: repeat-x;
        filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#563d7c', endColorstr='#6F5499', GradientType=0);
    }
    .bs-docs-header .container {
        position: relative;
    }
    @media (min-width: 992px)
        .bs-docs-header h1, .bs-docs-header p {
        margin-right: 380px;
    }
    @media (min-width: 768px)
        .bs-docs-header h1 {
        font-size: 60px;
        line-height: 1;
    }
    .bs-docs-header h1 {
        margin-top: 0;
        color: #fff;
    }
    .bs-docs-header h1, .bs-docs-header p {
        margin-right: 380px;
    }
    .bs-docs-header p {
        margin-bottom: 0;
        font-weight: 300;
        line-height: 1.4;
    }
</style>

<div class="bs-docs-header" id="content">
  <div class="container">
    <h1>Components</h1>
    <p>Lorem ipsum ad his scripta blandit partiendo, eum fastidii accumsan euripidis in, eum liber hendrerit an. Qui ut wisi vocibus suscipiantur, quo dicit ridens inciderint id.</p>
  </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-md-4">
            <h1 id="dropdowns" class="page-header">{{ product }}</h1>

            <div class="panel panel-default">
              <div class="panel-heading">
                  <div class="panel-title">
                  <i class="glyphicon glyphicon-usd pull-right"></i>
                  <h4>Realizar compra</h4>
                  </div>
              </div>
              <div class="panel-body">
                <form class="form form-vertical" action="{% url 'market:pay' %}">
                  <div class="control-group">
                    <label>Email</label>
                    <div class="controls">
                     <input type="text" class="form-control" placeholder="Enter email" id="email" name="email">
                    </div>
                  </div>
                  <div class="control-group">
                      <label></label>
                      <div class="controls">
                          <button type="submit" class="btn btn-success">
                            Comprar!
                          </button>
                      </div>
                  </div>
                  <div class="control-group">
                    <label>Pay Address</label>
                    <div class="controls">
                     <input type="text" class="form-control" placeholder="Pay Address" disabled id="address" name="address">
                    </div>
                  </div>
                </form>
            </div>
          </div>
        </div>
    </div>
</div>

{% endblock %}

bitplace/templates/right-column.html
    <div class="col-md-9">

      <!-- column 2 -->
      <ul class="list-inline pull-right">
         <li><a href="#"><i class="glyphicon glyphicon-cog"></i></a></li>
         <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="glyphicon glyphicon-comment"></i><span class="count">3</span></a><ul class="dropdown-menu" role="menu"><li><a href="#">1. Is there a way..</a></li><li><a href="#">2. Hello, admin. I would..</a></li><li><a href="#"><strong>All messages</strong></a></li></ul></li>
         <li><a href="#"><i class="glyphicon glyphicon-user"></i></a></li>
         <li><a title="Add Widget" data-toggle="modal" href="#addWidgetModal"><span class="glyphicon glyphicon-plus-sign"></span> Add Widget</a></li>
      </ul>
      <a href="#"><strong><i class="glyphicon glyphicon-dashboard"></i> My Dashboard</strong></a>

        <hr>

        <div class="row">



            <!-- center left-->
            <div class="col-md-6">
              <div class="well">Inbox Messages <span class="badge pull-right">3</span></div>

              <hr>

              <div class="btn-group btn-group-justified">
                <a href="#" class="btn btn-primary col-sm-3">
                  <i class="glyphicon glyphicon-plus"></i><br>
                  Service
                </a>
                <a href="#" class="btn btn-primary col-sm-3">
                  <i class="glyphicon glyphicon-cloud"></i><br>
                  Cloud
                </a>
                <a href="#" class="btn btn-primary col-sm-3">
                  <i class="glyphicon glyphicon-cog"></i><br>
                  Tools
                </a>
                <a href="#" class="btn btn-primary col-sm-3">
                  <i class="glyphicon glyphicon-question-sign"></i><br>
                  Help
                </a>
              </div>

              <hr>

              <div class="panel panel-default">
                  <div class="panel-heading"><h4>Reports</h4></div>
                  <div class="panel-body">

                    <small>Success</small>
                    <div class="progress">
                      <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="72" aria-valuemin="0" aria-valuemax="100" style="width: 72%">
                        <span class="sr-only">72% Complete</span>
                      </div>
                    </div>
                    <small>Info</small>
                    <div class="progress">
                      <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100" style="width: 20%">
                        <span class="sr-only">20% Complete</span>
                      </div>
                    </div>
                    <small>Warning</small>
                    <div class="progress">
                      <div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%">
                        <span class="sr-only">60% Complete (warning)</span>
                      </div>
                    </div>
                    <small>Danger</small>
                    <div class="progress">
                      <div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100" style="width: 80%">
                        <span class="sr-only">80% Complete</span>
                      </div>
                    </div>

                  </div><!--/panel-body-->
              </div><!--/panel-->

              <hr>

              <!--tabs-->
              <div class="container">
                <div class="col-md-4">
                <ul class="nav nav-tabs" id="myTab">
                  <li class="active"><a href="#profile" data-toggle="tab">Profile</a></li>
                  <li><a href="#messages" data-toggle="tab">Messages</a></li>
                  <li><a href="#settings" data-toggle="tab">Settings</a></li>
                </ul>

                <div class="tab-content">
                  <div class="tab-pane active" id="profile">
                    <h4><i class="glyphicon glyphicon-user"></i></h4>
                    Lorem profile dolor sit amet, consectetur adipiscing elit. Duis pharetra varius quam sit amet vulputate.
                    <p>Quisque mauris augue, molestie tincidunt condimentum vitae, gravida a libero. Aenean sit amet felis
                      dolor, in sagittis nisi.</p>
                  </div>
                  <div class="tab-pane" id="messages">
                    <h4><i class="glyphicon glyphicon-comment"></i></h4>
                    Message ipsum dolor sit amet, consectetur adipiscing elit. Duis pharetra varius quam sit amet vulputate.
                    <p>Quisque mauris augu.</p>
                  </div>
                  <div class="tab-pane" id="settings">
                    <h4><i class="glyphicon glyphicon-cog"></i></h4>
                    Lorem settings dolor sit amet, consectetur adipiscing elit. Duis pharetra varius quam sit amet vulputate.
                    <p>Quisque mauris augue, molestie.</p>
                  </div>
                </div>
                </div>
              </div>

              <!--/tabs-->

              <hr>

              <div class="panel panel-default">
                  <div class="panel-heading"><h4>New Requests</h4></div>
                  <div class="panel-body">
                    <div class="list-group">
                    <a href="#" class="list-group-item active">Hosting virtual mailbox serv..</a>
                    <a href="#" class="list-group-item">Dedicated server doesn't..</a>
                    <a href="#" class="list-group-item">RHEL 6 install on new..</a>
                    </div>
                  </div>
              </div>

            </div><!--/col-->
            <div class="col-md-6">
                <div class="panel panel-default">
                  <div class="panel-heading"><h4>Notices</h4></div>
                  <div class="panel-body">

                  <div class="alert alert-info">
                    <button type="button" class="close" data-dismiss="alert">×</button>
                    This is a dismissable alert.. just sayin'.
                  </div>

                  This is a dashboard-style layout that uses Bootstrap 3. You can use this template as a starting point to create something more unique.
                  <br><br>
                  Visit the Bootstrap Playground at <a href="http://bootply.com">Bootply</a> to tweak this layout or discover more useful code snippets.
                  </div>
                </div>

                <table class="table table-striped">
                      <thead>
                        <tr><th>Visits</th><th>ROI</th><th>Source</th></tr>
                      </thead>
                      <tbody>
                        <tr><td>45</td><td>2.45%</td><td>Direct</td></tr>
                        <tr><td>289</td><td>56.2%</td><td>Referral</td></tr>
                        <tr><td>98</td><td>25%</td><td>Type</td></tr>
                        <tr><td>..</td><td>..</td><td>..</td></tr>
                        <tr><td>..</td><td>..</td><td>..</td></tr>
                      </tbody>
                </table>

                <div class="panel panel-default">
                    <div class="panel-heading">
                        <div class="panel-title">
                        <i class="glyphicon glyphicon-wrench pull-right"></i>
                        <h4>Post Request</h4>
                        </div>
                    </div>
                    <div class="panel-body">

                      <form class="form form-vertical">

                        <div class="control-group">
                          <label>Name</label>
                          <div class="controls">
                           <input type="text" class="form-control" placeholder="Enter Name">
                          </div>
                        </div>

                        <div class="control-group">
                          <label>Message</label>
                          <div class="controls">
                            <textarea class="form-control"></textarea>
                          </div>
                        </div>

                        <div class="control-group">
                          <label>Category</label>
                          <div class="controls">
                             <select class="form-control"><option>options</option></select>
                          </div>
                        </div>

                        <div class="control-group">
                            <label></label>
                            <div class="controls">
                            <button type="submit" class="btn btn-primary">
                              Post
                            </button>
                            </div>
                        </div>

                      </form>


                  </div><!--/panel content-->
                </div><!--/panel-->

                <div class="panel panel-default">
                  <div class="panel-heading"><div class="panel-title"><h4>Engagement</h4></div></div>
                  <div class="panel-body">
                    <div class="col-xs-4 text-center"><img src="http://placehold.it/80/BBBBBB/FFF" class="img-circle img-responsive"></div>
                    <div class="col-xs-4 text-center"><img src="http://placehold.it/80/EFEFEF/555" class="img-circle img-responsive"></div>
                    <div class="col-xs-4 text-center"><img src="http://placehold.it/80/EEEEEE/222" class="img-circle img-responsive"></div>
                  </div>
               </div><!--/panel-->

            </div><!--/col-span-6-->